#34448 improved sqlite uniqueness checks
When the incremental path cache sync runs, toolkit will determine what to update via the data in the database, then pull down the updates from shotgun and lastly updates the database.

There is no acidity or transactions around this because of the Shotgun API, so there is a possibility that two syncs run in parallel and both end up deciding that they should insert a row in the db representing a new object that exists in shotgun but not yet in the db.

This used to result in errors due to the unique db constraint:

sqlite3.IntegrityError: columns entity_type, entity_id, root, path, primary_entity are not unique

This fix fixes that issue by gracefully falling back on the sql level by doing a INSERT OR IGNORE INTO, meaning if the record exists, it is skipped.

Also added several concurrency tests as part of trying to create a decent test for the fix above. Unfortunately i wasn't able to add a good test for this particular issue, but added two other concurrently multi process sync tests.

Closes #344