#28670 Better details for duplicate template errors When an error is raised because more than one template matches a path, we now display the templates as well as the fields that matched to help you determine what the offending key/values are. For example:
```
TankError: 2 templates are matching the path '/sgtk/projects/scarlet/sequences/001/000/Comp/publish/nuke/hawaii.v001.nk'.
The overlapping templates are:
<Sgtk TemplatePath nuke_shot_rdc_publish: sequences/{Sequence}/{Shot}/{Step}/publish/nuke/{foo}.v{version}.nk>
{'Step': 'Comp', 'foo': 'hawaii', 'Shot': '000', 'version': 1, 'Sequence': '001'}
<Sgtk TemplatePath nuke_shot_publish: sequences/{Sequence}/{Shot}/{Step}/publish/nuke/{name}.v{version}.nk>
{'Step': 'Comp', 'version': 1, 'Shot': '000', 'name': 'hawaii', 'Sequence': '001'}
```

closes #140